config/routes.rb
Rails.application.routes.draw do
  root to: "questions#index"

  devise_for :users
  resources :questions do
    member do
      put "like", to: "questions#upvote"
      put "dislike", to:"questions#downvote"
  end
end
end

app/models/question.rb
class Question < ActiveRecord::Base
  acts_as_votable

  validates :option_a, :presence => true
  validates :option_b, :presence => true

  def average_a
    if (self.get_upvotes.size > 0)
      upvotes = self.get_upvotes.size.to_f
      total = self.votes_for.size.to_f
      result = (upvotes/total*100).round(2)
    else
      result = 0
    end
    return result
  end

  def average_b
    if (self.get_downvotes.size > 0)
      downvotes = self.get_downvotes.size.to_f
      total = self.votes_for.size.to_f
      result = (downvotes/total*100).round(2)
    else
      result = 0
    end
    return result
  end
end

app/models/user.rb
class User < ActiveRecord::Base

    enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def upvote
    @question = Question.find(params[:id])
    @question.upvote_by current_user
    flash[:notice] = "Upvote added to" + " " + @question.option_a
    redirect_to :back
  end


  def downvote
    @question = Question.find(params[:id])
    @question.downvote_by current_user
    flash[:notice] = "Upvote added to" + " " + @question.option_b
    redirect_to :back
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      respond_to do |format|
        format.html { redirect_to '/' }
        format.js
      end
    else
      render :new
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url}
      format.js
    end
  end

private
  def question_params
    params.require(:question).permit(:option_a, :option_b)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WouldYouRather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<div class ="container">
<div id="user nav">
      <div class="pull-right">

      <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong> 
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
    </div>
    <br>
    <h3>Would you rather?</h3>
    <hr>
<body>

  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

<%= yield %>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<%= render "layouts/errors", :object => @question %>

<%= bootstrap_form_for @question, remote: true do |f| %>
  <%= f.text_field :option_a, label: "Option A" %>
  <%= f.text_field :option_b, label: "Option B" %>
<%= f.submit class: "btn btn-success" %>
<% end %>

app/views/questions/_question.html.erb
<ul class="list-unstyled well well-lg"  id="question_delete_<%= question.id %>">
  <li>
  <span class="lead"><%= link_to like_question_path(question), method: :put do %>
  <%= question.option_a %></span>
  <% end %>
  -<span class="text-info"> OR </span>-
  <span class="lead"><%= link_to dislike_question_path(question), method: :put do %>
  <%= question.option_b %></span>&nbsp;&nbsp;&nbsp;
<% end %>
<% if user_signed_in? && current_user.admin? %>
<span><small><%= link_to "(remove)", question, method: :delete, data: {confirm: "Are you sure?"}, remote: true, :class => 'text-danger' %></small></span>

<% end %>
</li>
  <br>
  <li>
    <div class="col-md-3">

    <div class="progress progress-striped active">
      <div class="progress-bar progress-bar-success" style="width: <%= question.average_a %>%"></div>
      <div class="progress-bar progress-bar-warning" style="width: <%= question.average_b %>%"></div>
    </div>
    </div>
  </li>
  <br>
  <br>

<%= question.get_upvotes.size %> | <%= question.average_a %> % &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <%= question.get_downvotes.size %> | <%= question.average_b %> %
  </ul>

app/views/questions/create.js.erb
$('#new_question').remove();
$('#new_link').show();
$('#questions').append('<%= j render(@question) %>');

app/views/questions/destroy.js.erb
$('#question_delete_<%= @question.id %>').remove();

app/views/questions/index.html.erb
<%= link_to "New Question", new_question_path, id: "new_link", remote: true, :class => "btn btn-success btn-xs" %>


<div class="questions" id="questions">
<h3>Questions</h3>
<%= render @questions %>
</div>

app/views/questions/new.html.erb
<h3>Would you rather...</h3>


<%= render 'form' %>

app/views/questions/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');